name = "Tyranny's Modpack"
author = "Myon, Abikebuk"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4224db5645a1b2889f5911166b03cd445cc436890ea8cc200d437679098fa297"

[versions]
fabric = "0.14.22"
minecraft = "1.19.2"
